Feature carv2 242 note create another
exxcellent/davit pull request #10
Opened 2021-05-20 08:27 UTC by exx-Andreas

merge after feature_CARV2-239_dropdown-select

2021-05-21 10:36 UTC, fenglberger requested changes

2021-05-21 10:36 UTC, fenglberger commented on package.json
>      "@types/react-dom": "^16.9.0",
hier bitte auch die css änderungen und fomratierungssachen rausziehen

2021-05-27 12:27 UTC, exx-Andreas commented on package.json
>      "@types/react-dom": "^16.9.0",
Jetzt sollte es besser sein.

2021-05-27 12:38 UTC, fenglberger approved these changes

2021-05-27 12:54 UTC, merged