fixed data-setup view bug CARV2-244
exxcellent/davit pull request #11
Opened 2021-05-21 07:58 UTC by exx-Andreas

2021-05-21 10:39 UTC, fenglberger requested changes

2021-05-21 10:39 UTC, fenglberger commented on src/components/metaDataModel/DataModelController.tsx
> +            if (currentActorDatas.length <= 0) {
wie soll currentActorDatas.length < 0 sein? und warum dann push ?

2021-05-21 10:39 UTC, fenglberger approved these changes

2021-05-27 08:16 UTC, exx-Andreas commented on src/components/metaDataModel/DataModelController.tsx
> +            if (currentActorDatas.length <= 0) {
Hab die Funktion getActorDatasFromView nochmal überarbeitet.

Wir wollen an dieser Stelle, wenn Step Actor-Datas verfügbar sind keine Data-Setup Actor-Datas anzeigen.

Vllt sollten wir einen Selector im Slice schreiben der diese Unterscheidung für uns trifft?

2021-05-31 05:53 UTC, fenglberger approved these changes

2021-05-31 06:15 UTC, merged